name: Download and Commit GeoJSON file

on:
  schedule:
    - cron: '0 3 * * *'  # Run every day at 06:00 (UTC +3)
  
jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run download.py
        run: python download.py

      - name: Check if file has changed
        id: check_changes
        run: |
          git diff --exit-code --quiet || echo "File has changed"
      - name: Commit changes
        run: |
          git config --local user.email "nikos.methodios00@gmail.com"
          git config --local user.name pavmeth22
          git add el_gdf.geojson
          git commit -m "Update el_gdf.geojson" || echo "No changes to commit"
          git push
